### ISSUE TITLE
不知阁下知不知道virtualpiano

### ISSUE THREAD

**Issue by scottchennnnnnnn** [WarpPrism/AutoPiano#13]
https://virtualpiano.net
原创?

**Comment by WarpPrism** [comment]
1. 音频资源来自virtualpiano；键位保持一致（之前不同）
2. 请看看源码，有重复的部分算我输

**Comment by WarpPrism** [comment]
> https://virtualpiano.net
> 原创?

1. 音频资源来自virtualpiano；键位保持一致（之前不同）
2. 请看看源码，有重复的部分算我输
