### ISSUE TITLE
歌曲名：来自天堂的魔鬼

### ISSUE THREAD

**Issue by DLjun** [WarpPrism/AutoPiano#22]
歌曲名：来自天堂的魔鬼

琴谱（<br/> 代表换行）：
6~ 6~ 6~8 68 w~ 88<br/> 
890~ 0~ 0~q0q0~ 9~ 9~<br/>
876~ 6~  6868w~ 88<br/>
890~ 0~ 0~ 987<br/>
787678~ 77~ 55~<br/>
787678~ 77~ 55~<br/>
787678~ 89~8 0~ 97<br/>
787678~ 77~ 55~<br/>
歌词：
夜 里 做了美丽的 恶 梦<br/>
想清 醒 我缺抵不过 心 动<br/>
哦~ 梦 里 你是无底 的黑洞<br/>
我无力抗 拒 失 重<br/>
You took my heart away away away away
You took my heart away away away away
你就是传说来 自天 堂的 魔鬼
You took my heart away away away away
难度系数： 2
DLjun(凋零菌)

**Comment by WarpPrism** [comment]
已添加，待发布
