### ISSUE TITLE
Safari无法正常打开网页

### ISSUE THREAD

**Issue by simon300000** [WarpPrism/AutoPiano#33]
打开`https://www.autopiano.cn`后会跳转`https://www.autopiano.cn/upgradebrowser`,

似乎是通过window.AudioContext来判断跳转，然而不知道为什么，即使Safari的`window.AudioContext `不是`undefined`，也会被弄走，必须要手动返回才能使用网页

Safari: 13.0.2 (15608.2.30.1.1)

而且production的代码和这个repo的似乎不是一份，完全不知道怎么修复

希望可以得到修复

**Comment by WarpPrism** [comment]
昨天更新出问题了，今晚修复。先用chrome吧

**Comment by simon300000** [comment]
嘿嘿，那就好
