### ISSUE TITLE
回梦仙游——千年缘自由钢琴歌谱

### ISSUE THREAD

**Issue by xin97yuan** [WarpPrism/AutoPiano#40]
`歌曲名：回梦仙游——千年缘（仙剑奇侠传4主题曲）

琴谱（<br/> 代表换行）：

fdf fpd sapapou<br/> 
uos uoa poppfd<br/> 
fdf fpd sapapou<br/> 
uos uodfdop a<br/> 

e tyu uouty<br/> 
e tuy t e w<br/> 
e tyu uopouty<br/> 
e tuy t e e<br/> 

fdf fpd sapapou<br/> 
uos uoa poppfd<br/> 
fdf fpd sapapou<br/> 
uos uodfdop a<br/> 

oup<br/> 

难度系数： 4
贡献者名字或昵称：纷羽
贡献者个人主页：https://space.bilibili.com/2638505`

**Comment by suestring7** [comment]
回梦游仙。。。

**Comment by xin97yuan** [comment]
> 回梦游仙。。。

对着简谱拼了一个小时，如果觉得不错不妨点个赞，多谢啦

**Comment by WarpPrism** [comment]
即将收录这首歌，感谢

**Comment by xin97yuan** [comment]
> 即将收录这首歌，感谢

好的，也很高兴能有更多的人接触我喜欢的歌曲
