### ISSUE TITLE
冒险岛登录乐

### ISSUE THREAD

**Issue by jlasjfa** [WarpPrism/AutoPiano#55]
歌曲名：冒险岛登录乐

琴谱（<br/> 代表换行）：【】包着的为需要按住shift的键
【69ey】io<br/>
【58wt】i【o】<br/>
【58wt】i【o】<br/>
【69ey】ioi【y】<br/>
【69ey】io【opdopd】<br/>
【58wt】i【od】g【h】hg【d】<br/>
【59ey】i【os】s【pop】<br/>
【69ey】ios【p】s【s】s【sdh】hg【dh】hg【dh】h【hj】g<br/>
h【hjhdd】g【d】gh【dd】<br/>
【d】gh【h】hg【dh】hg【dh】h【hj】g<br/>
h【hjhdd】g【d】gh【dd】<br/>
s【s】s【sh】hg<br/>
h【hssd】gh【jh】<br/>

**Comment by WarpPrism** [comment]
已发布。现在可以直接在网站上提交乐谱了，右侧有详细的语法规则：

https://www.autopiano.cn/create/post
