### ISSUE TITLE
体验版网页打开是空白页

### ISSUE THREAD

**Issue by 1995hjh** [WarpPrism/AutoPiano#62]
[体验版网页](https://www.autopiano.cn/)打开是空白页，啥也没有

**现象：**
开始情况是有的电脑可以访问，有的不行；
然后现在是，都打不开了！！！

**报错：**
**net::ERR_ABORTED**

**建议：**
作者看看是不是web服务配置的问题

**Comment by hsh778205** [comment]
我现在是没有问题的

谷歌浏览器

**Comment by WarpPrism** [comment]
上午代理服务器挂了一段时间，目前已修复
