### ISSUE TITLE
配套键盘

### ISSUE THREAD

**Issue by happysmile12321** [WarpPrism/AutoPiano#63]
有没有人可以写一篇博客介绍基本的键盘的工作原理。想自制一个钢琴键盘。主要是映射按键。或者是其他思路。比如激光投影什么的?谢谢大家。

**Comment by WarpPrism** [comment]
MIDI键盘就行，输出标准MIDI信号，AutoPiano接受到信号后，会触发音符播放。

**Comment by happysmile12321** [comment]
> MIDI键盘就行，输出标准MIDI信号，AutoPiano接受到信号后，会触发音符播放。

有点贵，还是想自己做个。毕竟是搞程序的，喜欢折腾。
